### ISSUE TITLE
Please upgrade promptpay-qr to version 0.4.3.

### ISSUE THREAD

**Issue by dtinth** [PromptPay/promptpay.github.io#35]
Previous version contains a critical bug in the algorithm. For more information please see:

https://github.com/dtinth/promptpay-qr/releases/tag/v0.4.3

**Comment by PromptPay** [comment]
We have already fix this issue in develop-branch.

@dtinth You can see more here #34.

Thank you very much.

**Comment by PromptPay** [comment]
And now We approve this code and merged into master #36.

**Comment by dtinth** [comment]
Good to know, thanks!
